### ISSUE TITLE
How to get facial landmarks?

### ISSUE THREAD

**Issue by romasiugzdaite** [altunenes/scramblery#4]
I am trying out the scripts you provided, though get_facial_landmarks is not described on the webpage. :( 

How to define face area in the script. 

scramleimage worked for me, but nor scramble face, nor scramblevideo... and demo's does not work me either.

help!!!

**Comment by altunenes** [comment]
The face area is defined using a method called facial landmarks, which essentially maps out key points on the face. The script uses these points to create a "mask" over the face, which is then scrambled. If you're having issues with this part, could you let me know any specific error messages/screenshots you're seeing 🙂?

 Just to cover all our bases, have you made sure that all the necessary Python packages are installed? 🙂 Specifically, mediapipe and cv2 are crucial for face detection to work . You can install them using pip:

`pip install mediapipe`
`pip install opencv-python`

**Comment by romasiugzdaite** [comment]
hi Enes,

In the end I installed media pipe and opencv-python and it worked.
Now I am struggling with the same thing but in videos? Is it possible
already to do it in videos?

I have only 2 videos to scramble, could you help me, please!!

Roma
